# Runs conventional commit check on PR
name: Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  checks:
    name: Checks, builds and tests code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use node 16 and yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint Code
        run: yarn lint:all
      - name: Lint CSS
        run: yarn lint:style
